homework_3
Otus-DevOps-22-08/AleksandrKalitin_infra pull request #2
Opened 2022-09-16 14:11 UTC by AleksandrKalitin

2022-09-18 12:01 UTC, mrgreyves requested changes
Здравствуйте!)
Добавляем описание к пуллреквесту
![image](https://user-images.githubusercontent.com/34331259/190901022-afe94f42-2e22-4528-b779-fe4f3456b3f5.png)
Так же добавляем workflow который запускает тесты к вашему дз
Это нужно было сделать еще в предыдущем дз
ДЗ возвращаю на доработку

2022-09-19 07:11 UTC, AleksandrKalitin commented
Добавил изменения

2022-09-20 12:55 UTC, mrgreyves requested changes
Здравствуйте!)
У вас где то потерялись тесты
Нужно их добавить =)

2022-09-20 14:16 UTC, mrgreyves requested changes
А теперь смотрим на результаты тестов и вносим корректировки
К сожалению есть некоторые проблемы

2022-09-22 16:42 UTC, closed without merging